[package]
name = "stumble-agent"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "interest-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
stumble-core = { path = "../stumble-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
