[package]
name = "stumble-api"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
stumble-core = { path = "../stumble-core" }
stumble-sync = { path = "../stumble-sync" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
url.workspace = true
uuid.workspace = true
