[package]
name = "stumble-mcp"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
stumble-core = { path = "../stumble-core" }
stumble-sync = { path = "../stumble-sync" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
